In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Name':['Alice','Bob','Charlie'],
    'Age':[25,30,35],
    'City':['New York','Paris','London']
    }
print(data)

{'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35], 'City': ['New York', 'Paris', 'London']}

In [3]:
df = pd.DataFrame(data)

In [4]:
print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   35    London

In [5]:
data = np.array([
    [1,'Alice',30],
    [2,'Bob',25],
    [3,'Cjarlie',35]
])

In [6]:
df = pd.DataFrame(data)

In [7]:
df = pd.DataFrame(data, columns=['ID','Name','Age'])
print(df)

  ID     Name Age
0  1    Alice  30
1  2      Bob  25
2  3  Cjarlie  35

In [8]:
df=pd.read_csv('C:/Users/silst/OneDrive/바탕 화면/excelfile/국영수.csv',header=0,encoding='cp949')
df_c=pd.read_csv('C:/Users/silst/OneDrive/바탕 화면/excelfile/국영수.csv',header=None,encoding='cp949')

In [9]:
df

   국어  영어  수학 체육
0  50  88  21  상
1  41  87  54  중
2  85  65  84  상
3  61  85  13  중
4  54  41  21  하
5  84  47  87  하
6  77  98  65  상
7  87  58  54  중
8  54  22  78  히

In [10]:
df_c

    0   1   2   3
0  국어  영어  수학  체육
1  50  88  21   상
2  41  87  54   중
3  85  65  84   상
4  61  85  13   중
5  54  41  21   하
6  84  47  87   하
7  77  98  65   상
8  87  58  54   중
9  54  22  78   히

In [11]:
df.shape

(9, 4)

In [12]:
df.columns

Index(['국어', '영어', '수학', '체육'], dtype='object')

In [13]:
df.dtypes

국어     int64
영어     int64
수학     int64
체육    object
dtype: object

In [14]:
df.describe()

              국어         영어         수학
count   9.000000   9.000000   9.000000
mean   65.888889  65.666667  53.000000
std    17.467430  25.729361  28.583212
min    41.000000  22.000000  13.000000
25%    54.000000  47.000000  21.000000
50%    61.000000  65.000000  54.000000
75%    84.000000  87.000000  78.000000
max    87.000000  98.000000  87.000000

In [16]:
df.head()

   국어  영어  수학 체육
0  50  88  21  상
1  41  87  54  중
2  85  65  84  상
3  61  85  13  중
4  54  41  21  하

In [17]:
df.tail()

   국어  영어  수학 체육
4  54  41  21  하
5  84  47  87  하
6  77  98  65  상
7  87  58  54  중
8  54  22  78  히

In [21]:
df.isnull().sum()

국어    0
영어    0
수학    0
체육    0
dtype: int64

In [20]:
df['체육'].value_counts()

체육
상    3
중    3
하    2
히    1
Name: count, dtype: int64

In [22]:
df['체육'].unique()

array(['상', '중', '하', '히'], dtype=object)

In [63]:
df['체육'].nunique()

4

In [24]:
#error
df[0]

KeyError: 0

In [25]:
df['국어']

0    50
1    41
2    85
3    61
4    54
5    84
6    77
7    87
8    54
Name: 국어, dtype: int64

In [26]:
df["합계"] = df["국어"] + df["영어"]
df

   국어  영어  수학 체육   합계
0  50  88  21  상  138
1  41  87  54  중  128
2  85  65  84  상  150
3  61  85  13  중  146
4  54  41  21  하   95
5  84  47  87  하  131
6  77  98  65  상  175
7  87  58  54  중  145
8  54  22  78  히   76

In [27]:
columns = ["국어","영어","수학"]
selected_columns = df[columns]
selected_columns

   국어  영어  수학
0  50  88  21
1  41  87  54
2  85  65  84
3  61  85  13
4  54  41  21
5  84  47  87
6  77  98  65
7  87  58  54
8  54  22  78

In [28]:
df.loc[:,"영어"]

0    88
1    87
2    65
3    85
4    41
5    47
6    98
7    58
8    22
Name: 영어, dtype: int64

In [81]:
columns = ["국어","영어","수학"]
selected_columns = df.loc[:,columns]
selected_columns

   국어  영어  수학
0  50  88  21
1  41  87  54
2  85  65  84
3  61  85  13
4  54  41  21
5  84  47  87
6  77  98  65
7  87  58  54
8  54  22  78

In [29]:
df

   국어  영어  수학 체육   합계
0  50  88  21  상  138
1  41  87  54  중  128
2  85  65  84  상  150
3  61  85  13  중  146
4  54  41  21  하   95
5  84  47  87  하  131
6  77  98  65  상  175
7  87  58  54  중  145
8  54  22  78  히   76

In [30]:
df.drop(["체육"],axis=1)

   국어  영어  수학   합계
0  50  88  21  138
1  41  87  54  128
2  85  65  84  150
3  61  85  13  146
4  54  41  21   95
5  84  47  87  131
6  77  98  65  175
7  87  58  54  145
8  54  22  78   76

In [31]:
data = {
    'A':[1,2,3,4],
    'B':[4.1,3.5,2.1,5.7],
    'C':['one','two','three','four']
}
df = pd.DataFrame(data)
df

   A    B      C
0  1  4.1    one
1  2  3.5    two
2  3  2.1  three
3  4  5.7   four

In [35]:
df['A']=df['A'].astype(float)
df['B']=df['B'].astype(int)
df['C']=df['C'].astype('category')

In [33]:
df['C'].dtype

CategoricalDtype(categories=['four', 'one', 'three', 'two'], ordered=False, categories_dtype=object)

In [36]:
df

     A  B      C
0  1.0  4    one
1  2.0  3    two
2  3.0  2  three
3  4.0  5   four

In [38]:
df['A']=df['A'].astype('str')
df

     A  B      C
0  1.0  4    one
1  2.0  3    two
2  3.0  2  three
3  4.0  5   four

In [39]:
df['A'].dtype

dtype('O')

In [107]:
#문자를 num으로 변경할 떄 파이썬이 못알아먹음.
df['A']=df['A'].astype(int)

ValueError: invalid literal for int() with base 10: '1.0'

In [40]:
df = df.rename(columns={
    'A':'국어',
    'B':'영어',
    'C':'번호'
})
df

    국어  영어     번호
0  1.0   4    one
1  2.0   3    two
2  3.0   2  three
3  4.0   5   four

In [41]:
data = {
    'Numeric1':[1,np.nan,3,4],
    'Numeric2':[5,6,np.nan,8.2],
    'Categoty':['dog',np.nan,'cat','dog']
}

In [42]:
df = pd.DataFrame(data)

In [43]:
A=df.select_dtypes(include=["number"]).columns
A

Index(['Numeric1', 'Numeric2'], dtype='object')

In [44]:
df[A]

   Numeric1  Numeric2
0       1.0       5.0
1       NaN       6.0
2       3.0       NaN
3       4.0       8.2

In [45]:
B=df.select_dtypes(include=['object','category']).columns
B

Index(['Categoty'], dtype='object')

In [46]:
df[B]

  Categoty
0      dog
1      NaN
2      cat
3      dog

In [47]:
df[A].fillna(df[A].median())

   Numeric1  Numeric2
0       1.0       5.0
1       3.0       6.0
2       3.0       6.0
3       4.0       8.2

In [48]:
df[A].fillna(df[A].mean())

   Numeric1  Numeric2
0  1.000000       5.0
1  2.666667       6.0
2  3.000000       6.4
3  4.000000       8.2

In [169]:
df

   Numeric1  Numeric2 Categoty
0       1.0       5.0      dog
1       NaN       6.0      NaN
2       3.0       NaN      cat
3       4.0       8.2      dog

In [51]:
df1 = pd.DataFrame({
    'a':['a0','a1','a2','a3'],
    'b':['b0','b1','b2','b3'],
    'c':['c0','c1','c2','c3']
})
df2 = pd.DataFrame({
    'a':['a2','a3','a4','a5'],
    'b':['b2','b3','b4','b5'],
    'c':['c2','c3','c4','c5'],
    'd':['d2','d3','c4','c5']
})

In [52]:
pd.concat([df1,df2],axis=0)

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
0  a2  b2  c2   d2
1  a3  b3  c3   d3
2  a4  b4  c4   c4
3  a5  b5  c5   c5

In [53]:
pd.concat([df1,df2],axis=1)

    a   b   c   a   b   c   d
0  a0  b0  c0  a2  b2  c2  d2
1  a1  b1  c1  a3  b3  c3  d3
2  a2  b2  c2  a4  b4  c4  c4
3  a3  b3  c3  a5  b5  c5  c5

In [54]:
pd.concat([df[A],df[B]],axis=1)

   Numeric1  Numeric2 Categoty
0       1.0       5.0      dog
1       NaN       6.0      NaN
2       3.0       NaN      cat
3       4.0       8.2      dog

In [57]:
df[(df['Numeric2']>=6) & (df['Numeric2'] <= 10)]

   Numeric1  Numeric2 Categoty
1       NaN       6.0      NaN
3       4.0       8.2      dog

In [58]:
df[(df['Numeric2']>=6) | (df['Numeric2'] <= 10)]

   Numeric1  Numeric2 Categoty
0       1.0       5.0      dog
1       NaN       6.0      NaN
3       4.0       8.2      dog

In [59]:
import numpy as np
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])
print(np.vstack(array1, array2))
print(np.hstack(array1, array2))

TypeError: vstack() takes 1 positional argument but 2 were given

In [7]:
import numpy as np
dict = {"Numeric1" : [1,np.nan,3,4], 
       'Numeric2' : [5,6,np.nan,9.2]}

dict.fillna(dict.median())
# DataFrame형태로 바꾼 후 채워 줄 수 있

AttributeError: 'dict' object has no attribute 'fillna'