In [10]:
import pandas as pd

df = pd.read_csv("program_1.csv", encoding = "utf-8-sig")
print(df.head())

  코드  프로그램1  프로그램2  프로그램3  프로그램4
0  A     57   24.0   85.0   47.0
1  B     56   98.0   65.0    0.0
2  C     62   89.0    NaN   66.0
3  D     54    NaN   94.0   54.0
4  E     54   54.0   47.0   84.0

In [1]:
num_df = df.select_dtypes(include='number')

num_df = num_df.fillna(num_df.mean())

num_df

NameError: name 'df' is not defined

In [25]:
obj_df = df.select_dtypes(include='object')

In [29]:
result = pd.concat([obj_df,num_df], axis=1)

result

  코드  프로그램1  프로그램2  프로그램3  프로그램4
0  A     57   24.0   85.0   47.0
1  B     56   98.0   65.0    0.0
2  C     62   89.0   72.4   66.0
3  D     54   63.2   94.0   54.0
4  E     54   54.0   47.0   84.0
5  F     23   51.0   71.0   50.2

In [40]:
result["평균"] = (result['프로그램1'] + result['프로그램2'] + result['프로그램3'] + result['프로그램4'])/4
result

  코드  프로그램1  프로그램2  프로그램3  프로그램4     평균
0  A     57   24.0   85.0   47.0  53.25
1  B     56   98.0   65.0    0.0  54.75
2  C     62   89.0   72.4   66.0  72.35
3  D     54   63.2   94.0   54.0  66.30
4  E     54   54.0   47.0   84.0  59.75
5  F     23   51.0   71.0   50.2  48.80

In [48]:
def categorize(result):
    if 0<result<=55:
        return "하"
    elif 55<result<=70:
        return "중"
    elif 71<result:
        return "상"

result["평가분류"]= result["평균"].apply(categorize)
result

  코드  프로그램1  프로그램2  프로그램3  프로그램4     평균 평가분류
0  A     57   24.0   85.0   47.0  53.25    하
1  B     56   98.0   65.0    0.0  54.75    하
2  C     62   89.0   72.4   66.0  72.35    상
3  D     54   63.2   94.0   54.0  66.30    중
4  E     54   54.0   47.0   84.0  59.75    중
5  F     23   51.0   71.0   50.2  48.80    하

In [56]:
filter_result_contains = result[result['평가분류'].str.contains('상', na=False)]
filter_result_contains

  코드  프로그램1  프로그램2  프로그램3  프로그램4     평균 평가분류
2  C     62   89.0   72.4   66.0  72.35    상