In [123]:
import pandas as pd
df = pd.read_csv("sample_1.csv", encoding = "utf-8-sig")

In [124]:
df["입실일자"] = pd.to_datetime(df["입실일자"],format='%Y%m%d', errors='coerce')
df["입실시각"] = pd.to_datetime(df["입실시각"],format='%H%M', errors='coerce').dt.time
df["퇴실일자"] = pd.to_datetime(df["퇴실일자"],format='%Y%m%d', errors='coerce')
df["퇴실시각"] = pd.to_datetime(df["퇴실시각"],format='%H%M', errors='coerce').dt.time
df["접수일자"] = pd.to_datetime(df["접수일자"],format='%Y%m%d', errors='coerce')
df

,연구번호,입실일자,입실시각,검사코드,검사코드NM,검사결과값(숫자),검사결과값(표시),기준치상한값,기준치하한값,접수일자,접수시각,검사나이,진료과코드,진료과코드NM,퇴실시각,퇴실일자,환자생년월,성별코드,성별코드NM
0,1219300234,2021-02-20,13:50:00,ZF0156,"ABGA coding (Des),Artery blood",342.0,342,NaN,NaN,2021-02-21,212123.0,81.0,NR,신경과,14:30:00,2021-03-02,193909,M,남성
1,1219300234,2021-02-20,13:50:00,ZF0016,"Bicarbonate (Qn),Artery blood",27.5,27.5,29.0,23.0,2021-02-21,212123.0,81.0,PSY,정신건강의학과,14:30:00,2021-03-02,193909,M,남성
2,1219300234,2021-02-20,13:50:00,ZF0155,"ABGA interpretation (Des),Artery blood",NaN,이전 동맥혈액 가스검사 판독결과가 Uncompensated respiratory a...,NaN,NaN,2021-02-21,43234.0,81.0,NR,신경과,14:30:00,2021-03-02,193909,M,남성
3,1219300234,2021-02-20,13:50:00,BB0007,"pO2 (Qn)[EM],Artery blood",117.8,117.8,108.0,83.0,2021-02-22,45628.0,81.0,PSY,정신건강의학과,14:30:00,2021-03-02,193909,M,남성
4,1219300234,2021-02-20,13:50:00,ZF0012,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,2021-02-22,45628.0,81.0,PSY,정신건강의학과,14:30:00,2021-03-02,193909,M,남성
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799995,1169043575,2020-05-19,18:00:00,ZF0157,"ABGA reading (Des),Artery blood",NaN,Normal ABGA,NaN,NaN,2020-05-20,155439.0,66.0,END,내분비내과,17:10:00,2020-05-20,195307,F,여성
799996,1169043575,2020-05-19,18:00:00,BC0202,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,2020-05-20,155439.0,66.0,GI,소화기내과,17:10:00,2020-05-20,195307,F,여성
799997,1169043575,2020-05-19,18:00:00,ZF0014,"Base excess (Qn),Artery blood",-1.8,-1.8,NaN,NaN,2020-05-20,155439.0,66.0,GS,일반외과,17:10:00,2020-05-20,195307,F,여성
799998,1169043575,2020-05-19,18:00:00,ZF0016,"Bicarbonate (Qn),Artery blood",22.9,22.9,29.0,23.0,2020-05-20,155439.0,66.0,INF,감염내과,17:10:00,2020-05-20,195307,F,여성
799999,1169043575,2020-05-19,18:00:00,BB0074,"Potassium (Qn)[POCT],Blood",3.7,3.7,NaN,NaN,2020-05-20,155439.0,66.0,NPH,신장내과,17:10:00,2020-05-20,195307,F,여성

In [125]:
df = df.drop(columns=['검사코드'], errors='ignore')
df = df.drop(columns=['진료과코드'], errors='ignore')
df = df.drop(columns=['진료과코드NM'], errors='ignore')
df = df.drop(columns=['성별코드NM'], errors='ignore')
df

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),검사결과값(표시),기준치상한값,기준치하한값,접수일자,접수시각,검사나이,퇴실시각,퇴실일자,환자생년월,성별코드
0,1219300234,2021-02-20,13:50:00,"ABGA coding (Des),Artery blood",342.0,342,NaN,NaN,2021-02-21,212123.0,81.0,14:30:00,2021-03-02,193909,M
1,1219300234,2021-02-20,13:50:00,"Bicarbonate (Qn),Artery blood",27.5,27.5,29.0,23.0,2021-02-21,212123.0,81.0,14:30:00,2021-03-02,193909,M
2,1219300234,2021-02-20,13:50:00,"ABGA interpretation (Des),Artery blood",NaN,이전 동맥혈액 가스검사 판독결과가 Uncompensated respiratory a...,NaN,NaN,2021-02-21,43234.0,81.0,14:30:00,2021-03-02,193909,M
3,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",117.8,117.8,108.0,83.0,2021-02-22,45628.0,81.0,14:30:00,2021-03-02,193909,M
4,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,2021-02-22,45628.0,81.0,14:30:00,2021-03-02,193909,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799995,1169043575,2020-05-19,18:00:00,"ABGA reading (Des),Artery blood",NaN,Normal ABGA,NaN,NaN,2020-05-20,155439.0,66.0,17:10:00,2020-05-20,195307,F
799996,1169043575,2020-05-19,18:00:00,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,2020-05-20,155439.0,66.0,17:10:00,2020-05-20,195307,F
799997,1169043575,2020-05-19,18:00:00,"Base excess (Qn),Artery blood",-1.8,-1.8,NaN,NaN,2020-05-20,155439.0,66.0,17:10:00,2020-05-20,195307,F
799998,1169043575,2020-05-19,18:00:00,"Bicarbonate (Qn),Artery blood",22.9,22.9,29.0,23.0,2020-05-20,155439.0,66.0,17:10:00,2020-05-20,195307,F
799999,1169043575,2020-05-19,18:00:00,"Potassium (Qn)[POCT],Blood",3.7,3.7,NaN,NaN,2020-05-20,155439.0,66.0,17:10:00,2020-05-20,195307,F

In [126]:
df['접수시각'] = ""
df

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),검사결과값(표시),기준치상한값,기준치하한값,접수일자,접수시각,검사나이,퇴실시각,퇴실일자,환자생년월,성별코드
0,1219300234,2021-02-20,13:50:00,"ABGA coding (Des),Artery blood",342.0,342,NaN,NaN,2021-02-21,,81.0,14:30:00,2021-03-02,193909,M
1,1219300234,2021-02-20,13:50:00,"Bicarbonate (Qn),Artery blood",27.5,27.5,29.0,23.0,2021-02-21,,81.0,14:30:00,2021-03-02,193909,M
2,1219300234,2021-02-20,13:50:00,"ABGA interpretation (Des),Artery blood",NaN,이전 동맥혈액 가스검사 판독결과가 Uncompensated respiratory a...,NaN,NaN,2021-02-21,,81.0,14:30:00,2021-03-02,193909,M
3,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",117.8,117.8,108.0,83.0,2021-02-22,,81.0,14:30:00,2021-03-02,193909,M
4,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,2021-02-22,,81.0,14:30:00,2021-03-02,193909,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799995,1169043575,2020-05-19,18:00:00,"ABGA reading (Des),Artery blood",NaN,Normal ABGA,NaN,NaN,2020-05-20,,66.0,17:10:00,2020-05-20,195307,F
799996,1169043575,2020-05-19,18:00:00,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,2020-05-20,,66.0,17:10:00,2020-05-20,195307,F
799997,1169043575,2020-05-19,18:00:00,"Base excess (Qn),Artery blood",-1.8,-1.8,NaN,NaN,2020-05-20,,66.0,17:10:00,2020-05-20,195307,F
799998,1169043575,2020-05-19,18:00:00,"Bicarbonate (Qn),Artery blood",22.9,22.9,29.0,23.0,2020-05-20,,66.0,17:10:00,2020-05-20,195307,F
799999,1169043575,2020-05-19,18:00:00,"Potassium (Qn)[POCT],Blood",3.7,3.7,NaN,NaN,2020-05-20,,66.0,17:10:00,2020-05-20,195307,F

In [127]:
re = df["검사나이"]
result = pd.DataFrame(re)
result

        검사나이
0       81.0
1       81.0
2       81.0
3       81.0
4       81.0
...      ...
799995  66.0
799996  66.0
799997  66.0
799998  66.0
799999  66.0

[800000 rows x 1 columns]

In [128]:
def categorize(result):
    if 81<=result:
        return "80세이상"
    elif 80 == result:
        return "80세"
    elif 70<=result<=79:
        return "70대"
    elif 60<=result<=69:
        return "60대"
    elif 50<=result<=59:
        return "50대"
    elif 40<=result<=49:
        return "40대"
    elif 30<=result<=39:
        return "30대" 
    elif 20<=result<=29:
        return "20대"
    elif 10<=result<=19:
        return "10대"

In [129]:
result["검사나이"] = result["검사나이"].apply(categorize)

In [130]:
df["검사나이"] = result["검사나이"]
df

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),검사결과값(표시),기준치상한값,기준치하한값,접수일자,접수시각,검사나이,퇴실시각,퇴실일자,환자생년월,성별코드
0,1219300234,2021-02-20,13:50:00,"ABGA coding (Des),Artery blood",342.0,342,NaN,NaN,2021-02-21,,80세이상,14:30:00,2021-03-02,193909,M
1,1219300234,2021-02-20,13:50:00,"Bicarbonate (Qn),Artery blood",27.5,27.5,29.0,23.0,2021-02-21,,80세이상,14:30:00,2021-03-02,193909,M
2,1219300234,2021-02-20,13:50:00,"ABGA interpretation (Des),Artery blood",NaN,이전 동맥혈액 가스검사 판독결과가 Uncompensated respiratory a...,NaN,NaN,2021-02-21,,80세이상,14:30:00,2021-03-02,193909,M
3,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",117.8,117.8,108.0,83.0,2021-02-22,,80세이상,14:30:00,2021-03-02,193909,M
4,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,2021-02-22,,80세이상,14:30:00,2021-03-02,193909,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799995,1169043575,2020-05-19,18:00:00,"ABGA reading (Des),Artery blood",NaN,Normal ABGA,NaN,NaN,2020-05-20,,60대,17:10:00,2020-05-20,195307,F
799996,1169043575,2020-05-19,18:00:00,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,2020-05-20,,60대,17:10:00,2020-05-20,195307,F
799997,1169043575,2020-05-19,18:00:00,"Base excess (Qn),Artery blood",-1.8,-1.8,NaN,NaN,2020-05-20,,60대,17:10:00,2020-05-20,195307,F
799998,1169043575,2020-05-19,18:00:00,"Bicarbonate (Qn),Artery blood",22.9,22.9,29.0,23.0,2020-05-20,,60대,17:10:00,2020-05-20,195307,F
799999,1169043575,2020-05-19,18:00:00,"Potassium (Qn)[POCT],Blood",3.7,3.7,NaN,NaN,2020-05-20,,60대,17:10:00,2020-05-20,195307,F

In [131]:
df["입원기간"] = df["퇴실일자"] - df["입실일자"]
df

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),검사결과값(표시),기준치상한값,기준치하한값,접수일자,접수시각,검사나이,퇴실시각,퇴실일자,환자생년월,성별코드,입원기간
0,1219300234,2021-02-20,13:50:00,"ABGA coding (Des),Artery blood",342.0,342,NaN,NaN,2021-02-21,,80세이상,14:30:00,2021-03-02,193909,M,10 days
1,1219300234,2021-02-20,13:50:00,"Bicarbonate (Qn),Artery blood",27.5,27.5,29.0,23.0,2021-02-21,,80세이상,14:30:00,2021-03-02,193909,M,10 days
2,1219300234,2021-02-20,13:50:00,"ABGA interpretation (Des),Artery blood",NaN,이전 동맥혈액 가스검사 판독결과가 Uncompensated respiratory a...,NaN,NaN,2021-02-21,,80세이상,14:30:00,2021-03-02,193909,M,10 days
3,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",117.8,117.8,108.0,83.0,2021-02-22,,80세이상,14:30:00,2021-03-02,193909,M,10 days
4,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,2021-02-22,,80세이상,14:30:00,2021-03-02,193909,M,10 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799995,1169043575,2020-05-19,18:00:00,"ABGA reading (Des),Artery blood",NaN,Normal ABGA,NaN,NaN,2020-05-20,,60대,17:10:00,2020-05-20,195307,F,1 days
799996,1169043575,2020-05-19,18:00:00,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,2020-05-20,,60대,17:10:00,2020-05-20,195307,F,1 days
799997,1169043575,2020-05-19,18:00:00,"Base excess (Qn),Artery blood",-1.8,-1.8,NaN,NaN,2020-05-20,,60대,17:10:00,2020-05-20,195307,F,1 days
799998,1169043575,2020-05-19,18:00:00,"Bicarbonate (Qn),Artery blood",22.9,22.9,29.0,23.0,2020-05-20,,60대,17:10:00,2020-05-20,195307,F,1 days
799999,1169043575,2020-05-19,18:00:00,"Potassium (Qn)[POCT],Blood",3.7,3.7,NaN,NaN,2020-05-20,,60대,17:10:00,2020-05-20,195307,F,1 days

In [134]:
df = df.dropna(subset = ["기준치상한값"])
df = df.dropna(subset = ["기준치하한값"])
df

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),검사결과값(표시),기준치상한값,기준치하한값,접수일자,접수시각,검사나이,퇴실시각,퇴실일자,환자생년월,성별코드,입원기간
1,1219300234,2021-02-20,13:50:00,"Bicarbonate (Qn),Artery blood",27.5,27.5,29.0,23.0,2021-02-21,,80세이상,14:30:00,2021-03-02,193909,M,10 days
3,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",117.8,117.8,108.0,83.0,2021-02-22,,80세이상,14:30:00,2021-03-02,193909,M,10 days
4,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,2021-02-22,,80세이상,14:30:00,2021-03-02,193909,M,10 days
5,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,2021-02-22,,80세이상,14:30:00,2021-03-02,193909,M,10 days
9,1219300234,2021-02-20,13:50:00,"pCO2 (Qn)[EM],Artery blood",47.0,47,45.0,35.0,2021-02-21,,80세이상,14:30:00,2021-03-02,193909,M,10 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799991,1169043575,2020-05-19,18:00:00,"pO2 (Qn)[EM],Artery blood",92.5,92.5,108.0,83.0,2020-05-20,,60대,17:10:00,2020-05-20,195307,F,1 days
799992,1169043575,2020-05-19,18:00:00,"pCO2 (Qn)[EM],Artery blood",38.1,38.1,45.0,35.0,2020-05-20,,60대,17:10:00,2020-05-20,195307,F,1 days
799993,1169043575,2020-05-19,18:00:00,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,2020-05-20,,60대,17:10:00,2020-05-20,195307,F,1 days
799996,1169043575,2020-05-19,18:00:00,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,2020-05-20,,60대,17:10:00,2020-05-20,195307,F,1 days
799998,1169043575,2020-05-19,18:00:00,"Bicarbonate (Qn),Artery blood",22.9,22.9,29.0,23.0,2020-05-20,,60대,17:10:00,2020-05-20,195307,F,1 days

In [136]:
df["환자ID"] = (df["연구번호"].astype(str).str[:3] + df["연구번호"].astype(str).str[5:])
df

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),검사결과값(표시),기준치상한값,기준치하한값,접수일자,접수시각,검사나이,퇴실시각,퇴실일자,환자생년월,성별코드,입원기간,환자ID
1,1219300234,2021-02-20,13:50:00,"Bicarbonate (Qn),Artery blood",27.5,27.5,29.0,23.0,2021-02-21,,80세이상,14:30:00,2021-03-02,193909,M,10 days,12100234
3,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",117.8,117.8,108.0,83.0,2021-02-22,,80세이상,14:30:00,2021-03-02,193909,M,10 days,12100234
4,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,2021-02-22,,80세이상,14:30:00,2021-03-02,193909,M,10 days,12100234
5,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,2021-02-22,,80세이상,14:30:00,2021-03-02,193909,M,10 days,12100234
9,1219300234,2021-02-20,13:50:00,"pCO2 (Qn)[EM],Artery blood",47.0,47,45.0,35.0,2021-02-21,,80세이상,14:30:00,2021-03-02,193909,M,10 days,12100234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799991,1169043575,2020-05-19,18:00:00,"pO2 (Qn)[EM],Artery blood",92.5,92.5,108.0,83.0,2020-05-20,,60대,17:10:00,2020-05-20,195307,F,1 days,11643575
799992,1169043575,2020-05-19,18:00:00,"pCO2 (Qn)[EM],Artery blood",38.1,38.1,45.0,35.0,2020-05-20,,60대,17:10:00,2020-05-20,195307,F,1 days,11643575
799993,1169043575,2020-05-19,18:00:00,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,2020-05-20,,60대,17:10:00,2020-05-20,195307,F,1 days,11643575
799996,1169043575,2020-05-19,18:00:00,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,2020-05-20,,60대,17:10:00,2020-05-20,195307,F,1 days,11643575
799998,1169043575,2020-05-19,18:00:00,"Bicarbonate (Qn),Artery blood",22.9,22.9,29.0,23.0,2020-05-20,,60대,17:10:00,2020-05-20,195307,F,1 days,11643575